name: Publish Nuget

on:
  push:    
    branches:
      - master

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
    - name: bump-version
      uses: zwaldowski/match-label-action@v1
      with:
        allowed: major,minor,patch
    - name: next-version
      uses: zwaldowski/semver-release-action@v1
      with:
        bump: ${{ steps.bump-version.outputs.match }}
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Version Visual Studio SDK projects
      uses: roryprimrose/set-vs-sdk-project-version@v1.0.3
      with:
        version: ${{ steps.next-version.outputs.version }}
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
  publish:
    name: push
    needs: build-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: publish on version change
        uses: rohith/publish-nuget@v2
        with:
          PROJECT_FILE_PATH: src/NodaTime.EntityFrameworkCore.Conversions/NodaTime.EntityFrameworkCore.Conversions.csproj # Relative to repository root
          VERSION_STATIC: ${{ steps.next-version.outputs.version }}
          NUGET_KEY: ${{secrets.NUGET_API_KEY}} # API key for the NuGet feed
